Repository scipian/community, pull requests merged in 2019-03, with the labels that each got.

#1 Initial CONTRIBUTING documentation
  CONTRIBUTING.md
  templates/CONTRIBUTING.md.tpl
Labels: priority/medium, type/task

#15 Add Code of Conduct
  CODE-OF-CONDUCT.md
Labels: priority/medium, type/pull-request

#17 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  CONTRIBUTING.md
Labels: priority/medium, type/pull-request

#20 Clarify the RFC process
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
Labels: priority/high, status/assigned, type/pull-request

#21 Rename initiative label to rfc
  data/labels/type.json
Labels: status/assigned, type/pull-request
